theme: jekyll-theme-minimal
title: Alex Amiryan home
description: Alex Amiryan personal page
logo: https://i2.wp.com/www.amiryan.org/wp-content/uploads/2019/01/DSC_2288-2-1.jpg?resize=768%2C618&ssl=1
